service:
  name: keep-okr

yarnplugins:
  - serverless-offline

plugins:
  - serverless-hooks-plugin
  - serverless-ruby-package
  - serverless-ruby-layer

custom:
  region: ap-northeast-1
  rubyLayer:
    use_docker: true
    docker_file: Dockerfile
  hooks:
    package:initialize:
      # - docker run -v `pwd`:`pwd` -w `pwd` lambci/lambda:build-ruby2.5 gem install bundler:2.2.9 && gem install byebug --version 11.1.3 --source 'https://rubygems.org/' && bundle _2.2.9_ install --standalone --path vendor/bundle
      # - docker run -v `pwd`:`pwd` -w `pwd` lambci/lambda:build-ruby2.5 gem install bundler:2.2.9 && gem pristine byebug --version 11.1.3 && bundle _2.2.9_ install --standalone --path vendor/bundle
    # package:finalize:
    #   - rm -rf vendor
    #   - rm -rf .bundle

provider:
  name: aws
  runtime: ruby2.5
  stage: ${opt:stage, 'dev'}
  region: ${self:custom.region}

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: KeepOkr

functions:
  app:
    handler: lambda.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

package:
  include:
    - Gemfile.lock
    - Gemfile
    - config.ru
    - lambda.rb
    - config/**
    - app/**
